### ISSUE TITLE
Redesign arithmetics support

### ISSUE THREAD

**Issue by Toxaris** [Toxaris/pts#49]
@plmday is not happy about the current arithmetics support (see comment on 1ed3eaef2c71116ee6d06bfe0aaba03b238d1d70). In particular, the built-in type for arithmetics is called `Nat` but behaves like Haskell's `Integer`.

If we touch this, we should also fix `div`. It has two problems: It needs to round down its result, and it is partial because of division by zero.

**Comment by Blaisorblade** [comment]
This issue got diverted away — the latest discussions are in #114. Hence closing.
